version: '3'
services:
    fiscalcode:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: pontalti/fiscalcode
        container_name: fiscal-code
        ports:
          - "80:8080"
          - "8000:8000"
        networks: 
            - production-network
            
networks: 
    production-network:
        driver: bridge
