spring:
  devtools:
    remote.secret: teste 
    add-properties: true
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:h2:mem:pizza;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  h2:
    console.enabled: true
  sql:
    init:
      platform: h2
      mode: always
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method