apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-label
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}